/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iv127_maven_demo2_misc_Unsafe */

#ifndef _Included_com_iv127_maven_demo2_misc_Unsafe
#define _Included_com_iv127_maven_demo2_misc_Unsafe
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    allocateMemory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_allocateMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    freeMemory
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_freeMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    putInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_putInt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    getInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_getInt
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    putDouble
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_putDouble
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    getDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_getDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    putLong
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_putLong
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    getLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_getLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    putByte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_putByte
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     com_iv127_maven_demo2_misc_Unsafe
 * Method:    getByte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_com_iv127_maven_demo2_misc_Unsafe_getByte
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
