/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iv127_maven_demo2_App */

#ifndef _Included_com_iv127_maven_demo2_App
#define _Included_com_iv127_maven_demo2_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iv127_maven_demo2_App
 * Method:    doubleArrayAddViaRegionAccessor
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_App_doubleArrayAddViaRegionAccessor
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     com_iv127_maven_demo2_App
 * Method:    doubleArrayAddViaElementsAccessor
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_App_doubleArrayAddViaElementsAccessor
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     com_iv127_maven_demo2_App
 * Method:    doubleArrayAddViaCriticalAccessor
 * Signature: ([DD)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_App_doubleArrayAddViaCriticalAccessor
  (JNIEnv *, jclass, jdoubleArray, jdouble);

/*
 * Class:     com_iv127_maven_demo2_App
 * Method:    printStringUTF
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_App_printStringUTF
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iv127_maven_demo2_App
 * Method:    printStringCriticalUTF
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_App_printStringCriticalUTF
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_iv127_maven_demo2_App
 * Method:    registerNatives
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_App_registerNatives
  (JNIEnv *, jclass);

/*
 * Class:     com_iv127_maven_demo2_App
 * Method:    doubleAge
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_iv127_maven_demo2_App_doubleAge
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
