/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iv127_maven_demo2_Person */

#ifndef _Included_com_iv127_maven_demo2_Person
#define _Included_com_iv127_maven_demo2_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iv127_maven_demo2_Person
 * Method:    allocate0
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_iv127_maven_demo2_Person_allocate0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_iv127_maven_demo2_Person
 * Method:    free0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_Person_free0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iv127_maven_demo2_Person
 * Method:    getName0
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_iv127_maven_demo2_Person_getName0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iv127_maven_demo2_Person
 * Method:    getAge0
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_iv127_maven_demo2_Person_getAge0
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_iv127_maven_demo2_Person
 * Method:    sayHi0
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_iv127_maven_demo2_Person_sayHi0
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
