/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1java_example1_Dog */

#ifndef _Included_test1java_example1_Dog
#define _Included_test1java_example1_Dog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test1java_example1_Dog
 * Method:    bark
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_example1_Dog_bark
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
