/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1java_TestNative */

#ifndef _Included_test1java_TestNative
#define _Included_test1java_TestNative
#ifdef __cplusplus
extern "C" {
#endif
#undef test1java_TestNative_VALUE
#define test1java_TestNative_VALUE 1L
#undef test1java_TestNative_PRICE
#define test1java_TestNative_PRICE 2.5
#undef test1java_TestNative_IS_READY
#define test1java_TestNative_IS_READY 0L
/*
 * Class:     test1java_TestNative
 * Method:    isOdd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_test1java_TestNative_isOdd
  (JNIEnv *, jobject, jint);

/*
 * Class:     test1java_TestNative
 * Method:    linspace
 * Signature: (DDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_test1java_TestNative_linspace
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     test1java_TestNative
 * Method:    sumOfDoubleArray
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_TestNative_sumOfDoubleArray
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     test1java_TestNative
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_TestNative_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     test1java_TestNative
 * Method:    ones
 * Signature: (II)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_test1java_TestNative_ones
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test1java_TestNative
 * Method:    max
 * Signature: ([[D)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_TestNative_max
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     test1java_TestNative
 * Method:    speak
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_TestNative_speak__
  (JNIEnv *, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    speak
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_TestNative_speak__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     test1java_TestNative
 * Method:    nativePrintln
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_nativePrintln
  (JNIEnv *, jobject, jstring);

/*
 * Class:     test1java_TestNative
 * Method:    nativeConcat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_TestNative_nativeConcat
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     test1java_TestNative
 * Method:    printPerson
 * Signature: (Ltest1java/Person;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printPerson
  (JNIEnv *, jobject, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    printStaticPerson
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printStaticPerson
  (JNIEnv *, jclass);

/*
 * Class:     test1java_TestNative
 * Method:    setPerson
 * Signature: (Ltest1java/Person;Ljava/lang/String;ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_setPerson
  (JNIEnv *, jclass, jobject, jstring, jint, jstring, jint);

/*
 * Class:     test1java_TestNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_init
  (JNIEnv *, jclass);

/*
 * Class:     test1java_TestNative
 * Method:    callPersonMethods
 * Signature: (Ltest1java/Person;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_callPersonMethods
  (JNIEnv *, jclass, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    freeMemory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_test1java_TestNative_freeMemory
  (JNIEnv *, jclass);

/*
 * Class:     test1java_TestNative
 * Method:    createPerson
 * Signature: (Ljava/lang/String;I)Ltest1java/Person;
 */
JNIEXPORT jobject JNICALL Java_test1java_TestNative_createPerson__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     test1java_TestNative
 * Method:    animalSpeak
 * Signature: (Ltest1java/example1/Animal;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_TestNative_animalSpeak
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     test1java_TestNative
 * Method:    printNumInfo
 * Signature: (Ljava/lang/Number;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printNumInfo
  (JNIEnv *, jclass, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    printNameField
 * Signature: (Ltest1java/Person;Ljava/lang/reflect/Field;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printNameField
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    printNameMethod
 * Signature: (Ltest1java/Person;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printNameMethod
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    printConstants
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printConstants
  (JNIEnv *, jclass);

/*
 * Class:     test1java_TestNative
 * Method:    azabs
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_TestNative_azabs
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     test1java_TestNative
 * Method:    createInner
 * Signature: (Ltest1java/TestNative;)Ltest1java/TestNative/InnerClass;
 */
JNIEXPORT jobject JNICALL Java_test1java_TestNative_createInner
  (JNIEnv *, jclass, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    createNested
 * Signature: ()Ltest1java/TestNative/NestedClass;
 */
JNIEXPORT jobject JNICALL Java_test1java_TestNative_createNested
  (JNIEnv *, jclass);

/*
 * Class:     test1java_TestNative
 * Method:    exceptionDemo
 * Signature: (ZZZ)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_exceptionDemo
  (JNIEnv *, jclass, jboolean, jboolean, jboolean);

/*
 * Class:     test1java_TestNative
 * Method:    createPerson
 * Signature: ()Ltest1java/Person;
 */
JNIEXPORT jobject JNICALL Java_test1java_TestNative_createPerson__
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
