/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1java_TestNative */

#ifndef _Included_test1java_TestNative
#define _Included_test1java_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test1java_TestNative
 * Method:    isOdd
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_test1java_TestNative_isOdd
  (JNIEnv *, jobject, jint);

/*
 * Class:     test1java_TestNative
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_TestNative_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     test1java_TestNative
 * Method:    speak
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_TestNative_speak__
  (JNIEnv *, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    speak
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_TestNative_speak__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     test1java_TestNative
 * Method:    linspace
 * Signature: (DDI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_test1java_TestNative_linspace
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     test1java_TestNative
 * Method:    sumOfDoubleArray
 * Signature: ([D)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_TestNative_sumOfDoubleArray
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     test1java_TestNative
 * Method:    ones
 * Signature: (II)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_test1java_TestNative_ones
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     test1java_TestNative
 * Method:    max
 * Signature: ([[D)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_TestNative_max
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     test1java_TestNative
 * Method:    nativePrintln
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_nativePrintln
  (JNIEnv *, jobject, jstring);

/*
 * Class:     test1java_TestNative
 * Method:    nativeConcat
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_TestNative_nativeConcat
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     test1java_TestNative
 * Method:    printPerson
 * Signature: (Ltest1java/Person;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printPerson
  (JNIEnv *, jobject, jobject);

/*
 * Class:     test1java_TestNative
 * Method:    printStaticPerson
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_printStaticPerson
  (JNIEnv *, jclass);

/*
 * Class:     test1java_TestNative
 * Method:    setPerson
 * Signature: (Ltest1java/Person;Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_test1java_TestNative_setPerson
  (JNIEnv *, jclass, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
