/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1java_AiryFunction */

#ifndef _Included_test1java_AiryFunction
#define _Included_test1java_AiryFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test1java_AiryFunction
 * Method:    ai
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_AiryFunction_ai
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     test1java_AiryFunction
 * Method:    bi
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_test1java_AiryFunction_bi
  (JNIEnv *, jclass, jdouble);

#ifdef __cplusplus
}
#endif
#endif
