/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test1java_example1_Animal */

#ifndef _Included_test1java_example1_Animal
#define _Included_test1java_example1_Animal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test1java_example1_Animal
 * Method:    bark
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test1java_example1_Animal_bark
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
